### ISSUE TITLE
Doesn't compile against Gerrit plugin API 2.11-SNAPSHOT

### ISSUE THREAD

**Issue by davido** [dluksza/secure-store-jasypt#1]
Running `mvn package` is failing with

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project secure-store-jasypt: Compilation failure: Compilation failure:
[ERROR] /home/davido/projects/secure-store-jasypt/src/main/java/com/collabnet/gerrit/SecureStoreJasypt.java:[39,39] error: no interface expected here

```

Was it based on old `secure-store` implementation? On most recent master `SecureStore` is interface and not class, i think.

**Comment by dluksza** [comment]
It is based on most recent version that is currenlty under [review](https://gerrit-review.googlesource.com/#/q/status:open+project:gerrit+branch:master+topic:secure-store-lib).

**Comment by davido** [comment]
I see. Now, following the docs, the site was created, but immediately after the site was created gerrit is failing to start, because dependency library is missing in the `$site_path/lib`:

```
Initialized /home/davido/projects/test_site_encrypted
Executing /home/davido/projects/gerrit/../test_site_encrypted/bin/gerrit.sh start
Starting Gerrit Code Review: FAILED
error: cannot start Gerrit: exit status 1
```

After copying of the `jasypt-1.9.2.jar` to `$site_path/lib` the gerrit can be started.

**Comment by dluksza** [comment]
This was described in readme. But it shouldn't be a problem to build jar with dependencies (jasypt jar is not signed) then this step could be skipped. Will update maven configuration to build so called uberjar instead of "plain" jar file

**Comment by dluksza** [comment]
Additonal step of putting jasypt into lib/ dir is no longer required
